### PR TITLE
make dao.delete(clazz, where) a bit more flexible

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by wrandall22** [comment]
Ah, that's a nice way to remove my hack in the other branch.

**Comment by wrandall22** [comment]
If we merge this first I can use it in the group_by branch. :+1:

**Comment by frett** [comment]
yup, saw it and figured I should add that support in natively :)

**Comment by frett** [comment]
going to merge since travis has no reason to fail on this.

**Pull request merged**
