### PR TITLE
remove newrelic support module

### PR DESCRIPTION
**Pull request by frett**
this functionality is no longer necessary, we use Fabric IO for crash reporting and that has native support for logging arbitrary exceptions

### CODE REVIEW

**Comment by wrandall22** [comment]
Was newrelic only being used for crash reporting? I guess it's not like a server where it can monitor jvm, etc.

**Comment by frett** [comment]
new relic originally had 2 purposes, crash reporting and monitoring of http api calls. The first purpose was completely replaced by crashlytics which is a much nicer solution, but new relic still has usages for monitoring http calls.

I'm actually thinking about including newrelic in MPDX

**Comment by frett** [comment]
The logic removed here was logic to log an arbitrary exception without triggering an actual app crash. This is provided natively by Crashlytics, see: https://github.com/CruGlobal/mpdx-android/blob/master/mpdx-app/src/main/java/org/mpdx/android/db/MpdxDatabase.java#L92

**Comment by wrandall22** [comment]
:+1:

**Pull request merged**
